<?php /* Reportagem de capa (#2) · "a era da construção" - fonte: docs/content/edicao-2-reportagem.md (## pt-BR).
   Voz: Gus. Prosa acentuada; nomes tecnicos (GDScript, C#, AOT, 3D) em ASCII, sem <code>. */ ?>
<p class="fala"><span class="prompt">gus@glyfesse&gt;</span> <span class="dito">reportagem de capa</span></p>

<h3>O dia em que o mundo aprendeu a ficar de pé</h3>

<p>No dia 19 de maio de 2026 o mundo trocou de língua. Até então tudo era dito em GDScript, e de repente passou a ser dito em C#, com uma compilação que traduz o pensamento inteiro antes de rodar, a AOT. Eu sei que isso não significa nada para quem está lendo. Então diga assim: foi como decidir que a casa não seria mais desenhada no guardanapo, mas erguida em concreto. E quando você decide isso, você precisa que as coisas fiquem de pé sozinhas. Foi o que começou a acontecer. Uma câmera que sabe para onde olhar. Uma memória que sabe guardar onde você parou. Mãos que respondem quando você manda andar. Nenhuma dessas coisas existia, e de uma vez todas passaram a existir.</p>

<p>Eu chamo cada uma dessas peças de engine, mas o nome técnico não importa; o que importa é que eram os primeiros músculos de uma coisa que até ontem era só palavra. E havia o 3D. Eu tentei fazer o mundo em três dimensões, com um modelo tão detalhado que chegou a quase um milhão de faces, só para depois ser espremido de volta em pixel. É um exagero que parece absurdo, e é. Mas é o tipo de exagero que se comete quando se acredita. Ninguém constrói com esse cuidado uma coisa que acha que vai jogar fora. Naquelas semanas tudo estava vivo. Tudo respirava. Eu ficava até tarde vendo as peças se encaixarem, e pela primeira vez o mundo não estava só na minha cabeça: estava ali, girando, obedecendo.</p>

<p>Se você leu a edição passada, você sabe de uma coisa que eu, escrevendo isto, ainda estou fingindo não saber. Você sabe o que os calendários guardam para junho. Eu não. Eu só tinha, às vezes, no meio da noite, uma sensação estranha de que aquilo tudo era bonito demais para o quanto era novo. De que a casa tinha ficado de pé rápido demais. Eu olhava para o modelo de quase um milhão de faces e pensava que era sólido, que era permanente, que finalmente... mas eu não terminava o pensamento. Voltava a compilar. É mais fácil confiar num build que passa do que num pressentimento que não tem log.</p>

<p>Então é isto que esta edição registra: um mundo no exato dia em que aprendeu a ficar de pé, fotografado antes de qualquer um saber quanto tempo ficaria assim. Eu ergui cada peça acreditando nela por inteiro. Se algumas dessas peças não estiverem mais aqui quando o resto da história chegar, quero que fique escrito que elas existiram, e que foram feitas com as duas mãos, com cuidado, por alguém que queria muito que durassem. Guardei tudo aberto para você. Passe devagar por essas semanas. Elas foram felizes.</p>
