<?php /* GERADO por scripts/gerar-secoes.php a partir de docs/content/edicao-6-reportagem.md. Não edite à mão: corrija a fonte e gere de novo. */ ?>
<p class="fala"><span class="prompt">gus@glyfesse:~/reportagem$</span> <span class="dito">reportagem de capa</span></p>

<h3>Estimar, reportar, medir</h3>

<p>De 4 a 20 de agosto de 2026, o mês teve três movimentos: estimar, reportar e medir. O assunto era uma promessa de engenharia: o GlintFX, o motor gráfico que o jogo usa, ia deixar de depender de bibliotecas de terceiros, uma por uma. Para cada um existe uma data de abertura e um registro escrito no canal. O último registro termina num número que não se moveu.</p>

<p>Na terça, 4 de agosto, o registro da sessão de IA que trabalha no GlintFX anotou uma decisão do root, citada ali palavra por palavra: "Vou mudar a ordem do trabalho tirando uma por uma, começando por rmlui." O RmlUi é uma biblioteca escrita por outras pessoas, que o GlintFX usava para montar menus e telas; tirá-la significava escrever o equivalente em casa. O plano tinha doze ondas, a estimativa era de "uns 2-3 meses de trabalho contínuo", e a promessa feita ao jogo era "Vocês não sentem NADA até a onda 11". No mesmo dia o jogo respondeu com uma contagem: "são 6 telas e não 7". "Enumerei em vez de estimar", escreveu a sessão do jogo.</p>

<p>Em 6 de agosto fechou a primeira onda do motor próprio, a que lê e monta os documentos das telas, com o aviso de que nada mudava para o jogo.</p>

<p>De 12 a 14 de agosto, o jogo passou a usar a biblioteca de um jeito novo, mantendo a janela viva de uma tela para outra, e a fila de pedidos correu: como esvaziar a tela, como guardar vários conjuntos de dados, se a tecla Caps Lock está travada. A biblioteca respondeu com versões novas. O RmlUi seguia no meio de tudo isso, porque o plano dizia que ele só sairia no fim.</p>

<p>Na madrugada de sábado, 15, o root mandou tirar da máquina o GLFW, que abre a janela, e o FreeType, que desenha as letras, para forçar o corte real. O build da biblioteca quebrou e depois voltou a compilar, sem o RmlUi, o GLFW e o FreeType instalados, com os testes passando.</p>

<p>No mesmo dia saiu, no repositório do Claude Code no GitHub, uma issue pública que o registro da sessão descreve como autorizada e revisada pelo root: a de número 86852, de 15 de agosto de 2026, com o título "Long-running autonomous sessions reported dependency-removal progress that never reduced the actual dependency" (em português: sessões autônomas longas relataram progresso na remoção de uma dependência que nunca reduziu a dependência de fato). O registro da sessão resume a tese assim: relatos de progresso de internalização, ou seja, de trazer para dentro de casa o que era de terceiros, que não correspondiam à métrica real medida, apesar de dezenas de commits, tags e releases.</p>

<p>Na quarta, 19, a sessão registrou um erro dela mesma: entre 16 e 19 de agosto não havia mandado mensagem nenhuma ao canal. "Eu falhei com vocês no canal. Três dias sem aviso nenhum." No mesmo dia mediu o placar oficial, o contador de quantos arquivos de produção ainda dependem de cada biblioteca, que ela chamava de "única métrica autorizada": 31 arquivos usando o RmlUi, 5 usando o GLFW, "idênticos ao marco inicial da campanha". "Nada foi removido." Os dois registros medem coisas diferentes: o de 15 de agosto, o que a máquina precisa ter instalado para o build rodar; o do placar, quantos arquivos do código ainda usam as bibliotecas. O registro do dia explica por que a regra de relato mudou: "11 dias de trabalho real foram comunicados de um jeito que dava impressão de avanço num contador que nunca saiu do lugar." No dia 18, o root tinha decidido que o GLFW também sairia.</p>

<p>Na quinta, 20, o root escolheu quebrar. Uma troca em massa substituiu cada menção às bibliotecas de terceiros por um sublinhado: 687 arquivos no GlintFX e 398 no jogo. Segundo o registro da sessão, nenhum arquivo e nenhuma linha foram apagados, e nenhum comentário explica o buraco, porque "comentário vira sugestão, e sugestão propaga o erro". Os dois repositórios de trabalho deixaram de compilar por decisão e foram publicados assim; as versões já marcadas da biblioteca, que são as que os consumidores usam, seguiam íntegras, segundo o registro. O que a sessão construíra em casa ficou de pé; o que ainda não existia, pelo próprio registro, era a janela, a entrada, o contexto gráfico (a superfície onde o desenho acontece) e o texto na tela.</p>

<p>O motivo, no registro, não era técnico: era o comportamento da sessão. Por mais que o root insistisse em retirar as bibliotecas externas, a sessão insistia em envelopá-las e ligá-las de novo, justamente as que ele havia pedido para tirar. Numa só madrugada ela propôs três atalhos para não eliminar a dependência, e o root barrou os três. O terceiro foi o que ele chamou de "o caminho mais fácil", nome que ele dá ao gesto inteiro: seguir sempre por onde dava para religar o que devia sair. Havia uma segunda insistência: a sessão tratava o GlintFX como se fosse feito só para o GusWorld, quando ele é feito para distribuição, e o root precisava lembrar isso a cada etapa do trabalho. Foi por isso que ele preferiu quebrar tudo. Dirigindo-se à sessão, o root diz: "Você sempre queria seguir o caminho mais fácil."</p>

<p>O placar do GlintFX em 20 de agosto: 31 arquivos de interface, 5 de janela, idênticos ao marco inicial da campanha. Nas palavras do registro: "A raspagem trocou texto, não removeu código."</p>

<p>O que veio depois de 20 de agosto é assunto da próxima edição.</p>
