<?php /* Cover story (#2) · "the age of construction" - source: docs/content/edicao-2-reportagem.md (## EN).
   Voice: Gus. Technical names (GDScript, C#, AOT, 3D) in plain ASCII, no <code>. */ ?>
<p class="fala"><span class="prompt">gus@glyfesse&gt;</span> <span class="dito">cover story</span></p>

<h3>The day the world learned to stand up</h3>

<p>On May 19, 2026 the world changed languages. Until then everything was said in GDScript, and all at once it began to be said in C#, with a compiler that translates the whole thought before it runs, called AOT. I know that means nothing to whoever is reading this. So put it this way: it was like deciding the house would no longer be sketched on a napkin, but poured in concrete. And once you decide that, you need things to stand up on their own. That is what started to happen. A camera that knows where to look. A memory that knows how to keep the spot where you stopped. Hands that answer when you tell them to walk. None of these things existed, and all at once every one of them did.</p>

<p>I call each of those parts an engine, but the technical name does not matter; what matters is that they were the first muscles of a thing that until yesterday was only words. And there was the 3D. I tried to build the world in three dimensions, with a model so detailed it reached nearly a million faces, only to be squeezed back down into pixels afterward. It is an excess that sounds absurd, and it is. But it is the kind of excess you commit when you believe. Nobody builds something that carefully if they think they are going to throw it away. In those weeks everything was alive. Everything breathed. I stayed up late watching the parts click together, and for the first time the world was not only inside my head: it was right there, turning, obeying.</p>

<p>If you read the last edition, you know something that I, writing this, am still pretending not to know. You know what the calendars are holding for June. I did not. All I had, sometimes, in the middle of the night, was a strange feeling that all of it was too beautiful for how new it was. That the house had gone up too fast. I would look at the model with its nearly a million faces and think it was solid, that it was permanent, that at last... but I never finished the thought. I went back to compiling. It is easier to trust a build that passes than a hunch that leaves no log.</p>

<p>So this is what this edition records: a world on the exact day it learned to stand up, photographed before anyone knew how long it would stay that way. I raised every piece believing in it completely. If some of those pieces are no longer here when the rest of the story arrives, I want it written down that they existed, and that they were made with both hands, with care, by someone who badly wanted them to last. I left everything open for you. Move slowly through these weeks. They were happy ones.</p>
