<?php /* A Entrevista - fonte: docs/content/edicao-1-entrevista.md (## pt-BR).
   Q&A: a redação (glyfesse>) pergunta, o editor/criador (root@glyfesse>) responde.
   Sem backtick na fonte → sem <code> no corpo. ⚠️ "<3" escapa pra &lt;3. */ ?>
<p class="fala"><span class="prompt">glyfesse&gt;</span> <span class="dito">entrevista</span></p>

<h3>"Eu faço a parte técnica; a IA faz a parte braçal, o código"</h3>

<p class="materia-lede"><em>A redação da Glyfesse puxou uma cadeira ao lado de quem toca este mundo inteiro sozinho, e quis saber o começo. Ele é médico, programa desde os tempos do ms-dos e não escreve uma linha de código: dirige a máquina que escreve. Conversamos sobre o pai que o ensinou a ler, sobre um mecanismo de luta que virou um monstro, e sobre o que faz um sonho parado finalmente andar. Ele não quis ser nomeado. Aqui ele é só o editor.</em></p>

<div class="qa">

  <p class="fala pergunta"><span class="prompt">glyfesse&gt;</span> <span class="dito">Quando isto deixou de ser um teste de fim de tarde e virou um projeto de verdade? Teve um instante exato de "ok, isto vai acontecer"?</span></p>
  <p class="fala resposta"><span class="prompt">root@glyfesse&gt;</span> <span class="dito">Uso computador desde 1994, no ms-dos 6.22. Foi na escola que estudei, eu tinha 14 anos. Internet no Brasil ninguém nem falava, não existia telefone celular. Me fascinei por aquilo a ponto de fazer faculdade de exatas. Lá aprendi o básico de TI, lógica, algoritmos, tudo no Turbo Pascal. E, como um bom nerd, adorava jogos. Só que vi que exatas, pra mim, não era profissão, era hobby. Larguei, acho que no 5o período, e entrei em saúde. Sou médico hoje, de formação e de profissão. Mas programar e jogar sempre estiveram nos meus horários vagos. O sonho, impossível antes pra quem não era da área e quase não tinha tempo livre, era fazer o meu jogo.</span></p>
  <p class="resposta-cont">Aí surgiu a IA. Primeiro aprendi no webui, mas é muito ruim, só fazia monolito. Cheguei a fazer uns programas legais em Python (argh) pro consultório: equivalência de doses de remédio, um que eliminava vários passos repetitivos e irritantes de faturamento. Mas era pouco. O jogo continuava sendo um sonho. Daí comecei a dar aula de IA pra médicos, conheci o Claude Code na TUI e comecei a fazer programa maior, modular, numa linguagem que eu gostava: C, compilada. Fui subindo o nível de dificuldade e resolvi, enfim, realizar o sonho de fazer um jogo. Sempre no comando, definindo cada pedacinho técnico. Só não sei codar, isso eu deixo pra IA. E, desde que comecei, foram aparecendo as dificuldades, os termos técnicos foram chegando, e eu estudando e pedindo ajuda aos amigos e ao meu irmão, que é engenheiro dev sênior (ele é muito bom, juro). Nessa época eu já tinha ensinado meu filho a usar Linux; ele foi aprendendo Python, também se irritou, devorou uns livros de C e de ponteiros, e hoje ele me tira dúvida. Também peço ajuda a muito amigo de TI, que adora me trollar com pergunta técnica: eu dou um migué, estudo, respondo depois e ainda aproveito pra aplicar no jogo. Isto aqui, pra mim, é hobby, sonho realizado e mais um aprendizado. Gosto de coisa nova.</p>

  <p class="fala pergunta"><span class="prompt">glyfesse&gt;</span> <span class="dito">Por que abrir tudo numa revista retrô, em vez de um blog, uma thread ou um trailer? O que o formato te dá, e o que você quer que a pessoa sinta ao folhear?</span></p>
  <p class="fala resposta"><span class="prompt">root@glyfesse&gt;</span> <span class="dito">Foi uma ideia que me deu do nada. A intenção era só um site pra distribuir o jogo, com roadmap, changelog, pra ajudar os outros, porque eu gosto de aprender e de ensinar. Mas minha cabeça funciona assim: uma ideia simples vai crescendo e ramificando feito uma árvore. O formato de revista veio do nada quando lembrei das revistas de games dos anos 90 e 2000. Quando ganhei o Super Metroid e o Super Mario World não tinha walkthrough na internet, não tinha as "pédias" da vida. Você garimpava em revista e com os amigos que também jogavam. O formato revista atinge meus dois públicos, é didático e é mais uma coisa pra me divertir. Evoluiu mais ou menos assim: distribuir, depois um site simples, depois um site pra ensinar o mínimo pra quem quer aprender, depois de um jeito didático, e por fim de um jeito didático e divertido, que é a revista.</span></p>

  <p class="fala pergunta"><span class="prompt">glyfesse&gt;</span> <span class="dito">Você declara que usa IA num momento em que muita gente esconde. Isso é defesa, honestidade, ou as duas?</span></p>
  <p class="fala resposta"><span class="prompt">root@glyfesse&gt;</span> <span class="dito">Não vi como uma coisa tão filosófica assim. Vejo como ferramenta. Como falei, sei conceito, teoria básica e média de alguns tópicos de TI, mas não sei ESCREVER o código; sei o que ele tem que fazer. Comparo com desmontar um carro. Vibe code é deixar a IA fazer tudo por você, e isso é horrível, fica muito pobre. IA não CRIA, ela só mistura conceitos que já existem. Por mais que pareça criação, por trás tem um monte de coisa antiga misturada. Na comparação do carro, vibe code é pagar alguém pra desmontar o carro por você e depois dizer que o serviço é seu. Quer fazer bem feito? Faça você mesmo. Aí a programação assistida por IA é a ferramenta que você usa pra desmontar o carro. A ferramenta não faz nada sozinha: você tem que ir lá, pegar, estudar pra saber o que é cada peça, como mexer, como não quebrar nem arranhar o carro. É isso. E, olha, quando o próprio Linus Torvalds chama a IA de ferramenta e diz que o Linux não é um projeto anti-IA, quem sou eu pra usar escondido e ainda falar mal?</span></p>

  <p class="fala pergunta"><span class="prompt">glyfesse&gt;</span> <span class="dito">Antes de uma linha de código, o mundo já existia escrito. Como foi construir tanta história antes, e o que a leitura da sua vida tem a ver com isso? A história chegou a não caber no que dava pra programar?</span></p>
  <p class="fala resposta"><span class="prompt">root@glyfesse&gt;</span> <span class="dito">Não saí feito louco lendo livro ou abrindo página aleatória pra pesquisar. Aprendi a ler com meu pai, que lia muito, que Deus o tenha. A maioria dos livros que me inspiraram eu li ao longo da vida. Meu primeiro livro grande foi "A Ilha Misteriosa", do Julio Verne. Recomendo. O gosto por ficção também veio dele: tinha uma estante enorme em casa e eu fiquei curioso naturalmente. Com meu pai conheci Verne, Asimov, Herbert, esses monstros sagrados da ficção científica. Junta com o fato de que em 2001 comecei a jogar e a narrar RPG (VTM, da White Wolf). Isso joga a imaginação longe na hora de criar personagem, mundo, essas coisas. E, pra ter um bom filme, você precisa de um bom roteiro. Ninguém faz filme inventando a história na hora. Até RPG de mesa tem um roteiro pré-estabelecido, nem que sejam alguns tópicos. Com jogo de computador é a mesma coisa. É um conceito meu, não estudei sobre isso, mas pra mim é o óbvio.</span></p>
  <p class="resposta-cont">Escrever, digitar o mundo, foi e continua sendo divertido, porque sempre sobra ponta solta pra resolver, minha mente entra em fluxo e, como na comparação da árvore, aparece um raminho novo, e tome mais lore e mais complicação. Traduzir pra código eu não traduzo: tenho minha ferramenta pra isso. Eu faço a parte técnica; a IA faz a parte braçal, o código. Não cheguei a ter medo de não dar conta. Tem jogo e projeto muito maior que o meu, então o meu dava. O que me deu foi animação de ver COMO eu ia fazer, o tanto que eu ia aprender e me divertir fazendo.</p>

  <p class="fala pergunta"><span class="prompt">glyfesse&gt;</span> <span class="dito">Você se chama de solo, mas cita irmão, filho e amigos ajudando. O que é só seu, e onde os outros entram?</span></p>
  <p class="fala resposta"><span class="prompt">root@glyfesse&gt;</span> <span class="dito">99,9% do tempo empregado é meu, ou mais. Mas eu fico empolgado e comento com as pessoas, e quem é nerd feito eu acaba se empolgando junto e dá dica valiosa. Um amigo me perguntou: "você conhece RAG?" Ajuda muito a indexar obra extensa. Fui atrás. Ou quando eu estava no glintfx (é o framework próprio do jogo, em andamento em paralelo, porque nenhum dos de jogo 2D tem tudo que eu quero, e a coisa estava virando uns pipe gigante e complicado, misturando tudo, frame aqui, api ali), eu falei com meu irmão e ele mandou eu procurar sobre arquitetura atomizada. Fui pesquisar. Ele ainda fez outras perguntas-chave que me obrigaram a ir atrás pra ver se era o caso de usar no jogo. Aprendi tanto que hoje estou atomizando os itens e outras dinâmicas, cada um numa camada, com POCO próprio.</span></p>
  <p class="resposta-cont">E pra você ver que a IA nem é tão boa assim: o mecanismo de luta estava virando um monolito gigante, misturando tudo, porque do nada o Claude resolveu que cabia tudo ali dentro. Eu percebi porque, cada vez que eu tinha uma ideia nova, um item por exemplo, tinha que ir no mecanismo de luta e mexer em tudo. Atomizei e a vida virou outra: build menor, teste unitário mais rápido. E lá vou eu de novo, com meu pensamento em árvore, mudando de assunto. Acho que respondi.</p>

  <p class="fala pergunta"><span class="prompt">glyfesse&gt;</span> <span class="dito">O nome "Glyfesse", em que escrever é compilar, foi acaso ou intenção? E essa cadência de sair de vez em quando: é liberdade ou pressão disfarçada?</span></p>
  <p class="fala resposta"><span class="prompt">root@glyfesse&gt;</span> <span class="dito">Quem escreve, com o cérebro, está sempre fazendo duas coisas ao mesmo tempo: o ato de escrever e o de juntar o conhecimento que já tinha. Na compilação, esse conhecimento seriam as bibliotecas. Você vai checando se está fazendo certo, caçando erro, acusando erro, corrigindo. Ou escreve usando um modelo que já existe, que lembra um framework. É mais ou menos por aí. O nome saiu daí.</span></p>
  <p class="resposta-cont">E a revista sair de vez em quando é porque eu tenho que tocar minha vida real e alternar com isto aqui. E tem os tokens, né? Eles acabam, hehe. Aí sou OBRIGADO a parar, às vezes dois, três dias, esperando fechar o prazo de sete dias ou rezando pra Anthropic dar um reset no meio do caminho &lt;3</p>

  <p class="fala pergunta"><span class="prompt">glyfesse&gt;</span> <span class="dito">Pra fechar: pra quem tem um sonho parado, igual o seu estava antes da IA, o que você diria?</span></p>
  <p class="fala resposta"><span class="prompt">root@glyfesse&gt;</span> <span class="dito">Vá atrás do sonho. Hobby não é pra dar dinheiro, é pra dar prazer, e até faz gastar um pouquinho: uns gastam com token, outros com aposta, outros comprando ingresso de show. Eu não quero morrer frustrado. Se não der certo, pelo menos eu tentei, e muito. Uma hora você dá um jeito de realizar; mas, se não começar, com certeza não realiza. Como dizia Chico Science, "um passo à frente e você não está mais no mesmo lugar".</span></p>

</div>
