<?php /* Reportagem de capa - fonte: docs/content/edicao-1-reportagem.md (## pt-BR).
   Voz: Gus. ⚠️ typos deliberados preservados: "fazme", "começnado". */ ?>
<p class="fala"><span class="prompt">gus@glyfesse&gt;</span> <span class="dito">reportagem de capa</span></p>

<h3>Um mundo inteiro, em texto, antes de uma única linha de código</h3>

<p>Antes de existir uma tela, existia um documento. Antes do documento, outro. E antes deles, centenas de milhares de palavras que ninguém tinha mandado ninguém escrever. O mundo do jogo não começou como código. Começou como lore. Eras inteiras, com datas, com causa e consequência encaixadas uma na outra. Um idioma com gramática de verdade, com regra de como se forma uma palavra, não só nomes bonitos jogados no mapa. Gente com passado. Grupos que discordam entre si por motivos que fazme sentido de dentro do mundo. Tudo isso escrito, revisado, guardado. Nenhuma linha compilava. Nada rodava. E mesmo assim já existia, do jeito que um livro fechado existe: por inteiro, esperando ser aberto.</p>

<p>O que eu queria que você sentisse aqui não é o enredo. É o tamanho. Um mundo que teve história antes de ter pixel. Que dava para ler antes de dar para jogar. Em engenharia isso tem nome. A lore é a especificação, o código é o build: você escreve o que a coisa é, depois manda a máquina montar. Só que a especificação aqui não é uma folha de requisitos. É uma biblioteca. São eras que ninguém vai visitar dentro do jogo e que mesmo assim estão lá, segurando por baixo o que aparece por cima, como a fundação que sustenta um prédio e nunca sai na foto. Eu li tudo antes de programar qualquer coisa. Talvez seja por isso que o mundo pareça grande demais para o tamanho da tela... mas isso é outra conversa.</p>

<p>É literalmente a escrita antes da compilação. O nome da revista diz isso, e a matéria de capa é a prova. Primeiro o mundo foi escrito, palavra por palavra, ano por ano, até ficar denso o bastante para valer a pena virar código. Só então a primeira linha rodou. Você está chegando exatamente no ponto de virada: o texto já existe inteiro, o build está começnado agora, ao vivo, e dá para acompanhar a coisa compilar do zero. A maior parte desse mundo você ainda não vai ver. Ela está aqui embaixo, escrita, esperando. Eu sei que está, porque fui eu que escrevi. E deixei tudo aberto, caso você queira ver o resto aparecer.</p>
