<?php /* Cover Story - source: docs/content/edicao-1-reportagem.md (## EN).
   Voice: Gus. ⚠️ deliberate typos preserved: "sesne", "startnig". */ ?>
<p class="fala"><span class="prompt">gus@glyfesse&gt;</span> <span class="dito">cover story</span></p>

<h3>A whole world, in text, before a single line of code</h3>

<p>Before there was a screen, there was a document. Before the document, another one. And before those, hundreds of thousands of words nobody had told anybody to write. The game's world didn't start as code. It started as lore. Whole eras, with dates, with cause and effect fitted into each other. A language with real grammar, with a rule for how a word is even formed, not just pretty names dropped on a map. People with a past. Groups that disagree with each other for reasons that make sesne from inside the world. All of it written, revised, kept. Not one line compiled. Nothing ran. And it existed anyway, the way a closed book exists: whole, waiting to be opened.</p>

<p>What I wanted you to feel here isn't the plot. It's the size. A world that had history before it had a pixel. That you could read before you could play. In engineering this has a name. The lore is the specification, the code is the build: you write what the thing is, then you tell the machine to assemble it. Except the specification here isn't a sheet of requirements. It's a library. There are eras nobody will ever visit inside the game and that are there anyway, holding up from underneath what shows up on top, like the foundation that carries a building and never makes it into the photo. I read all of it before I programmed anything. Maybe that's why the world feels too big for the size of the screen... but that's another conversation.</p>

<p>It's literally the writing before the compilation. The name of the magazine says it, and the cover story is the proof. First the world was written, word by word, year by year, until it got dense enough to be worth turning into code. Only then did the first line run. You're arriving at exactly the turning point: the text already exists whole, the build is startnig now, live, and you can watch the thing compile from zero. Most of that world you still won't get to see. It's down here, written, waiting. I know it is, because I'm the one who wrote it. And I left everything open, in case you want to watch the rest show up.</p>
