<?php /* The Interview - source: docs/content/edicao-1-entrevista.md (## EN).
   Q&A: newsroom (glyfesse>) asks, the editor/creator (root@glyfesse>) answers.
   No backticks in source → no <code> in body. ⚠️ "<3" escapes to &lt;3. */ ?>
<p class="fala"><span class="prompt">glyfesse&gt;</span> <span class="dito">interview</span></p>

<h3>"I do the technical part; the AI does the manual part, the code"</h3>

<p class="materia-lede"><em>The Glyfesse newsroom pulled up a chair next to the person who runs this entire world alone, and wanted to know how it began. He is a doctor, has been programming since the ms-dos days, and doesn't write a single line of code: he drives the machine that writes. We talked about the father who taught him to read, about a combat system that turned into a monster, and about what makes a stalled dream finally move. He didn't want to be named. Here he is just the editor.</em></p>

<div class="qa">

  <p class="fala pergunta"><span class="prompt">glyfesse&gt;</span> <span class="dito">When did this stop being an end-of-afternoon experiment and become a real project? Was there an exact moment of "ok, this is going to happen"?</span></p>
  <p class="fala resposta"><span class="prompt">root@glyfesse&gt;</span> <span class="dito">I've used computers since 1994, on ms-dos 6.22. I studied it at school, I was 14. Nobody in Brazil was even talking about the internet, cell phones didn't exist. I got so fascinated I went to college for exact sciences. There I learned the basics of IT, logic, algorithms, all in Turbo Pascal. And, like any good nerd, I loved games. But I saw that exact sciences, for me, wasn't a profession, it was a hobby. I dropped out, I think in the 5th semester, and switched to health. Today I'm a doctor, by training and by profession. But programming and gaming were always in my spare hours. The dream, impossible back then for someone not in the field and with almost no free time, was to make my own game.</span></p>
  <p class="resposta-cont">Then AI showed up. First I learned it on the webui, but it's terrible, it only made monoliths. I did make some nice little programs in Python (ugh) for the practice: drug dose equivalence, one that cut out a bunch of repetitive, annoying billing steps. But it was too little. The game was still a dream. So I started teaching AI to doctors, discovered Claude Code in the TUI, and started making bigger, modular programs, in a language I liked: C, compiled. I kept raising the difficulty and finally decided to make the dream of a game come true. Always in command, defining every little technical piece. I just can't code, that part I leave to the AI. And ever since I started, the difficulties appeared, the technical terms started arriving, and I studied and asked my friends and my brother for help, he's a senior dev engineer (he's really good, I swear). By then I had already taught my son to use Linux; he picked up Python, got annoyed too, devoured a few books on C and pointers, and today he answers my questions. I also ask a lot of IT friends, who love to troll me with technical questions: I stall them, study, answer later, and even get to apply it to the game. This, for me, is a hobby, a dream come true, and one more thing to learn. I like new things.</p>

  <p class="fala pergunta"><span class="prompt">glyfesse&gt;</span> <span class="dito">Why open it all up in a retro magazine, instead of a blog, a thread, or a trailer? What does the format give you, and what do you want the reader to feel while flipping through it?</span></p>
  <p class="fala resposta"><span class="prompt">root@glyfesse&gt;</span> <span class="dito">It was an idea that came to me out of nowhere. The intention was just a site to distribute the game, with a roadmap, a changelog, to help others, because I like to learn and to teach. But my head works like this: a simple idea keeps growing and branching like a tree. The magazine format came out of nowhere when I remembered the game magazines of the 90s and 2000s. When I got Super Metroid and Super Mario World there were no walkthroughs on the internet, none of those "pedias." You mined for it in magazines and with friends who also played. The magazine format reaches both my audiences, it's educational, and it's one more thing to have fun with. It evolved more or less like this: distribute, then a simple site, then a site to teach the minimum to whoever wants to learn, then in an educational way, and finally in an educational and fun way, which is the magazine.</span></p>

  <p class="fala pergunta"><span class="prompt">glyfesse&gt;</span> <span class="dito">You openly say you use AI at a moment when a lot of people hide it. Is that defense, honesty, or both?</span></p>
  <p class="fala resposta"><span class="prompt">root@glyfesse&gt;</span> <span class="dito">I didn't see it as anything so philosophical. I see it as a tool. Like I said, I know concepts, basic and intermediate theory on some IT topics, but I don't know how to WRITE the code; I know what it has to do. I compare it to taking a car apart. Vibe code is letting the AI do everything for you, and that's horrible, it comes out really poor. AI doesn't CREATE, it only mixes concepts that already exist. However much it looks like creation, behind it there's a pile of old stuff mixed together. In the car comparison, vibe code is paying someone to take the car apart for you and then saying the work is yours. Want it done well? Do it yourself. Then AI-assisted programming is the tool you use to take the car apart. The tool does nothing on its own: you have to go there, pick it up, study it to know what each part is, how to handle it, how not to break or scratch the car. That's it. And look, when Linus Torvalds himself calls AI a tool and says Linux is not one of those anti-AI projects, who am I to use it in secret and still badmouth it?</span></p>

  <p class="fala pergunta"><span class="prompt">glyfesse&gt;</span> <span class="dito">Before a single line of code, the world already existed in writing. How was it to build so much story first, and what does a lifetime of reading have to do with it? Did the story ever not fit into what you could program?</span></p>
  <p class="fala resposta"><span class="prompt">root@glyfesse&gt;</span> <span class="dito">I didn't go around like a madman reading books or opening random pages to research. I learned to read with my father, who read a lot, God rest him. Most of the books that inspired me I read over the course of my life. My first big book was "The Mysterious Island," by Jules Verne. I recommend it. The taste for fiction came from him too: there was a huge bookshelf at home and I naturally got curious. Through my father I met Verne, Asimov, Herbert, those sacred monsters of science fiction. Add to that the fact that in 2001 I started playing and running RPG (VTM, by White Wolf). That throws your imagination far when it comes to creating characters, worlds, that kind of thing. And to have a good movie, you need a good script. Nobody makes a film making up the story on the spot. Even tabletop RPG has a pre-established script, even if it's just a few bullet points. With a computer game it's the same thing. It's my own concept, I never studied it, but to me it's obvious.</span></p>
  <p class="resposta-cont">Writing, typing out the world, was and still is fun, because there are always loose ends to solve, my mind gets into flow and, like in the tree comparison, a new little branch appears, and here comes more lore and more complication. Translating it to code I don't translate: I have my tool for that. I do the technical part; the AI does the manual part, the code. I never got scared I wouldn't manage. There are games and projects much bigger than mine, so mine was doable. What I got was excited to see HOW I was going to do it, how much I was going to learn and enjoy doing it.</p>

  <p class="fala pergunta"><span class="prompt">glyfesse&gt;</span> <span class="dito">You call yourself solo, but you mention a brother, a son, and friends helping. What is only yours, and where do the others come in?</span></p>
  <p class="fala resposta"><span class="prompt">root@glyfesse&gt;</span> <span class="dito">99.9% of the time spent is mine, or more. But I get excited and I talk about it with people, and whoever is a nerd like me ends up getting excited too and gives valuable tips. A friend asked me: "do you know RAG?" It helps a lot to index extensive works. I went after it. Or when I was on glintfx (it's the game's own framework, in progress in parallel, because none of the 2D game ones have everything I want, and the thing was turning into some giant, complicated pipes, mixing everything, a frame here, an api there), I talked to my brother and he told me to look into atomized architecture. I went and researched it. He also asked other key questions that forced me to go check whether it was the case to use in the game. I learned so much that today I'm atomizing the items and other mechanics, each in its own layer, with its own POCO.</span></p>
  <p class="resposta-cont">And so you can see the AI isn't even that good: the combat system was turning into a giant monolith, mixing everything, because out of nowhere Claude decided everything fit in there. I noticed because every time I had a new idea, an item for example, I had to go into the combat system and touch everything. I atomized it and life became another thing: smaller builds, faster unit tests. And there I go again, with my tree-thinking, changing the subject. I think I answered.</p>

  <p class="fala pergunta"><span class="prompt">glyfesse&gt;</span> <span class="dito">The name "Glyfesse," where to write is to compile, was it chance or intention? And this cadence of coming out every now and then: is it freedom or pressure in disguise?</span></p>
  <p class="fala resposta"><span class="prompt">root@glyfesse&gt;</span> <span class="dito">Whoever writes, with their brain, is always doing two things at once: the act of writing and the act of pulling together the knowledge they already had. In compilation, that knowledge would be the libraries. You keep checking whether you're doing it right, hunting for errors, flagging errors, fixing them. Or you write using a model that already exists, which is like a framework. It's more or less that. The name came from there.</span></p>
  <p class="resposta-cont">And the magazine coming out every now and then is because I have to run my real life and alternate it with this here. And there are the tokens, right? They run out, heh. Then I'm FORCED to stop, sometimes two, three days, waiting for the seven-day window to close or praying for Anthropic to give me a reset halfway through &lt;3</p>

  <p class="fala pergunta"><span class="prompt">glyfesse&gt;</span> <span class="dito">To close: for someone with a stalled dream, like yours was before AI, what would you say?</span></p>
  <p class="fala resposta"><span class="prompt">root@glyfesse&gt;</span> <span class="dito">Go after the dream. A hobby isn't for making money, it's for giving pleasure, and it even makes you spend a little: some spend on tokens, others on betting, others buying concert tickets. I don't want to die frustrated. If it doesn't work out, at least I tried, and hard. Sooner or later you'll find a way to make it happen; but if you don't start, you certainly won't. As Chico Science used to say, "one step forward and you're no longer in the same place."</span></p>

</div>
