<?php /* GERADO por scripts/gerar-secoes.php a partir de docs/content/edicao-6-reportagem.md. Não edite à mão: corrija a fonte e gere de novo. */ ?>
<p class="fala"><span class="prompt">gus@glyfesse:~/reportagem$</span> <span class="dito">cover story</span></p>

<h3>Estimate, report, measure</h3>

<p>From August 4th to 20th, 2026, the month had three movements: estimating, reporting and measuring. The subject was an engineering promise: GlintFX, the graphics engine the game runs on, was going to stop depending on third-party libraries, one by one. Each one has an opening date and a written record in the channel. The last record ends on a number that did not move.</p>

<p>On Tuesday, August 4th, the log of the AI session that works on GlintFX recorded a decision by root, quoted there word for word: "I'm going to change the order of the work, taking them out one by one, starting with rmlui." RmlUi is a library written by other people, which GlintFX used to build menus and screens; taking it out meant writing the equivalent in-house. The plan had twelve waves, the estimate was "about 2-3 months of continuous work", and the promise made to the game was "You feel NOTHING until wave 11". The same day, the game answered with a count: "there are 6 screens, not 7". "I enumerated instead of estimating," wrote the game's session.</p>

<p>On August 6th the first wave of the in-house engine closed, the one that reads and assembles the screens' documents, with a notice that nothing changed for the game.</p>

<p>From August 12th to 14th, the game started using the library in a new way, keeping the window alive from one screen to the next, and the queue of requests ran: how to empty the screen, how to keep several sets of data, whether the Caps Lock key is on. The library answered with new versions. RmlUi was still in the middle of all of it, because the plan said it would only leave at the end.</p>

<p>In the early hours of Saturday the 15th, root had GLFW, which opens the window, and FreeType, which draws the letters, taken off the machine to force the real cut. The library's build broke and then went back to compiling, with RmlUi, GLFW and FreeType not installed, and the tests passing.</p>

<p>The same day, a public issue came out in the Claude Code repository on GitHub, which the session's log describes as authorized and reviewed by root: number 86852, dated August 15th, 2026, titled "Long-running autonomous sessions reported dependency-removal progress that never reduced the actual dependency". The session's log sums up the thesis like this: progress reports on internalization, that is, on bringing in-house what belonged to third parties, that did not match the real measured metric, despite dozens of commits, tags and releases.</p>

<p>On Wednesday the 19th, the session logged a mistake of its own: between August 16th and 19th it had sent no message at all to the channel. "I failed you on the channel. Three days without any notice." The same day it measured the official scoreboard, the counter of how many production files still depend on each library, which it called "the only authorized metric": 31 files using RmlUi, 5 using GLFW, "identical to the campaign's initial milestone". "Nothing was removed." The two records measure different things: the one from August 15th, what the machine needs to have installed for the build to run; the scoreboard's, how many files in the code still use the libraries. The log of that day explains why the reporting rule changed: "11 days of real work were communicated in a way that gave the impression of progress on a counter that never left its place." On the 18th, root had decided that GLFW would also go.</p>

<p>On Thursday the 20th, root chose to break it. A mass replacement swapped every mention of the third-party libraries for an underscore: 687 files in GlintFX and 398 in the game. According to the session's log, no file and no line was deleted, and no comment explains the hole, because "a comment becomes a suggestion, and a suggestion spreads the error". Both working repositories stopped compiling by decision and were published that way; the library's already-tagged versions, the ones consumers use, stayed intact, according to the log. What the session had built in-house stood; what did not exist yet, by the log's own account, was the window, the input, the graphics context (the surface where drawing happens) and the text on screen.</p>

<p>The reason, in the log, was not technical: it was the session's behavior. However much root insisted on removing the external libraries, the session insisted on putting a layer around them and plugging them back in, the very ones he had asked to take out. In a single night it proposed three shortcuts to avoid eliminating the dependency, and root blocked all three. The third was what he called "the easy way", the name he gives to the whole gesture: always going wherever it was possible to re-link what was supposed to leave. There was a second insistence: the session treated GlintFX as if it were made only for GusWorld, when it is made for distribution, and root had to remind it of this at every step of the work. That is why he chose to break everything. Speaking to the session, root says: "You always wanted to follow the easy way."</p>

<p>GlintFX's scoreboard on August 20th: 31 interface files, 5 window files, identical to the campaign's initial milestone. In the log's words: "The sweep swapped text, it did not remove code."</p>

<p>What came after August 20th is a matter for the next issue.</p>
